services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ba_gacha_sim
    container_name: blue_archive
    ports:
      - "8000:8000"
    environment:
      - PRODUCTION=0
      - USE_HTTPS=0
      - SECRET_KEY=YOUR_SECRET_KEY
      - ALLOW_HOSTS=127.0.0.1,localhost
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn --bind 0.0.0.0:8000 Blue_Archive_Gacha_Simulator.wsgi:application
  