# Generated by Django 5.2.4 on 2025-08-22 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('asset_id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_portrait_data', models.BinaryField(blank=True, null=True, verbose_name='Portrait')),
                ('asset_artwork_data', models.BinaryField(blank=True, null=True, verbose_name='Artwork')),
                ('asset_pair_hash', models.CharField(editable=False, max_length=64, unique=True)),
            ],
            options={
                'db_table': 'image_asset_table',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100, unique=True, verbose_name='School')),
                ('school_image', models.BinaryField(null=True, verbose_name='Logo')),
            ],
            options={
                'db_table': 'student_school_table',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('version_id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=100, unique=True, verbose_name='Version')),
            ],
            options={
                'db_table': 'student_version_table',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_rarity', models.PositiveIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★')])),
                ('student_is_limited', models.BooleanField(default=False)),
                ('asset_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_web.imageasset')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.school')),
                ('version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.version')),
            ],
            options={
                'db_table': 'student_table',
                'indexes': [models.Index(fields=['version_id'], name='student_tab_version_69bf51_idx'), models.Index(fields=['student_rarity'], name='student_tab_student_c99e1d_idx'), models.Index(fields=['school_id'], name='student_tab_school__b4f705_idx')],
                'unique_together': {('student_name', 'version_id')},
            },
        ),
    ]
