# Generated by Django 5.2.4 on 2025-10-08 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achievement_category',
            field=models.CharField(choices=[('COLLECTION', 'Collection'), ('MILESTONE', 'Milestone'), ('LUCK', 'Feats of Luck')], default='MILESTONE', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achievement_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achievement_key',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achievement_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='unlockachievement',
            name='achievement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.achievement', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='unlockachievement',
            name='unlock_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='unlockachievement',
            name='unlock_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
