# Generated by Django 5.2.4 on 2025-09-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gachabanner',
            name='banner_image',
            field=models.BinaryField(blank=True, null=True, verbose_name='Image'),
        ),
    ]
