# Generated by Django 5.2.4 on 2025-09-25 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gachatransaction',
            options={'ordering': ['-transaction_create_on'], 'verbose_name': 'Gacha Transaction', 'verbose_name_plural': 'Gacha Transactions'},
        ),
    ]
