# Generated by Django 5.2.4 on 2025-09-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0002_gachabanner_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gachabanner',
            name='banner_include_limited',
            field=models.BooleanField(default=False, help_text='If checked, limited-time students that match the versions above will be included.', verbose_name='Include Limited Students'),
        ),
        migrations.AddField(
            model_name='gachabanner',
            name='banner_include_version',
            field=models.ManyToManyField(help_text="Which student versions (e.g., Original, Summer) are in this banner's regular pool.", to='app_web.version', verbose_name='Included Student Versions'),
        ),
        migrations.AlterField(
            model_name='gachabanner',
            name='banner_pickup',
            field=models.ManyToManyField(blank=True, null=True, related_name='pickup_in_banners', to='app_web.student', verbose_name='Pickup Students'),
        ),
    ]
