# Generated by Django 5.2.4 on 2025-09-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0003_gachabanner_banner_include_limited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gachabanner',
            name='banner_pickup',
            field=models.ManyToManyField(blank=True, related_name='pickup_in_banners', to='app_web.student', verbose_name='Pickup Students'),
        ),
    ]
